import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "@/context/providers";
import PageLoaderWrapper from "@/components/PageLoaderWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fyree Magazine",
  description: "Generated by Omar Gehad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <Providers>
          <PageLoaderWrapper>
            <main>{children}</main>
          </PageLoaderWrapper>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
